### ISSUE TITLE
Sort archives by year

### ISSUE THREAD

**Issue by axilleas** [axilleas/pelican-uberspot#2]
Like http://www.macdrifter.com/archives.html

**Comment by born2discover** [comment]
Looking for a solution to this myself, I stumblet upon your issue here. I managed to solve it. Here's a sollution:

    {% for year, date_year in dates|groupby( 'date.year' )|sort(reverse=True) %}
            <h2 id="{{year}}">{{year}}</h2>
            <ul class="year">
            {% for article in date_year %}
                <li>
                    <a href="{{ SITEURL }}/{{ article.url }}" rel="bookmark" title="Permalink to {{ article.title|striptags }}">{{ article.title }}</a>
                    <time datetime="{{ article.date.isoformat() }}" pubdate>{{ article.locale_date }}</time>
                </li>
            {% endfor %}
            </ul>
    {% endfor %}

Hope it helps!

**Comment by axilleas** [comment]
Thanks a lot! I will definitely add it to the theme :)
